---
- name: Deploy Static Bindings and Domain Mappings
  hosts: localhost
  vars_files: vars.yml
  tasks:
  - name: Deploy Static Path Binding
    cisco.aci.aci_static_binding_to_epg:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ item.0 }}"
      encap_id: "{{ item.1 }}"
      deploy_immediacy: immediate
      interface_mode: trunk
      interface_type: switch_port
      pod_id: 2
      leafs: 207
      interface: '1/30'
      state: present
    delegate_to: localhost
    with_together:
      - "{{ epgs }}"
      - "{{ encaps }}"
  
  - name: Deploy Physical Domain to EPG Binding
    cisco.aci.aci_epg_to_domain:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ item }}"
      domain: Student
      domain_type: phys
      state: present
    delegate_to: localhost
    with_items:
      - "{{ epgs }}"