---
- import_playbook: input_validation.yml

- name: Deploy Application Profile and EPGs
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml
  
  tasks:
  - name: Associate EPG with VMM Domain
    delegate_to: localhost
    cisco.aci.aci_epg_to_domain:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      domain: "ACI-FAB2-LAB-Compute"
      domain_type: "vmm"
      tenant: "{{ aci.tenant }}"
      epg: "{{ item }}"
      ap: "{{ aci.ap }}"
      deploy_immediacy: "immediate"
      resolution_immediacy: "immediate"
      vm_provider: "vmware"
      state: "present"
    with_items:
      "{{ aci.epg }}"