---
- name: Deploy Full Logical Configuration
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml
  
  tasks:
  - name: Validate Input
    assert:
      that:
        - lab_name | regex_search("^lab[0-9]{1,3}-[0-9]{1,3}$")
      fail_msg: "Invalid lab_name variable entered, please correct and retry.  You entered: {{ lab_name }}"

  # - name: Create VRF
  #   cisco.aci.aci_vrf:
  #     host: "{{ aci_hostname }}"
  #     username: "{{ username }}"
  #     password: "{{ password }}"
  #     validate_certs: no
  #     vrf: "{{ vrf }}"
  #     tenant: "{{ tenant }}"
  #     policy_control_preference: unenforced
  #     policy_control_direction: ingress
  #     state: present
  #   delegate_to: localhost
  - name: test include
    include: deploy_vrf_bd.yml

  - name: Create Bridge Domain
    delegate_to: localhost
    cisco.aci.aci_bd:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      tenant: "{{ aci.tenant }}"
      bd: "{{ aci.bd }}"
      vrf: "{{ aci.vrf }}"
      state: "present"

  - name: Create Bridge Domain Subnet
    delegate_to: localhost
    cisco.aci.aci_bd_subnet:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      tenant: "{{ aci.tenant }}"
      bd: "{{ aci.bd }}"
      gateway: "{{ aci.gw }}"
      mask: "24"
      state: "present"
      scope: "shared"

  - name: Create AP
    cisco.aci.aci_ap:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      tenant: "{{ aci.tenant }}"
      ap: "{{ aci.ap }}"
      state: "present"
    delegate_to: localhost

  - name: Create EPG
    cisco.aci.aci_epg:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      tenant: "{{ tenant }}"
      ap: "{{ aci.ap }}"
      epg: "{{ aci.item }}"
      bd: "{{ aci.bd }}"
      preferred_group: "yes"
      state: "present"
    delegate_to: localhost
    with_items:
      "{{ aci.epg }}"