---
- name: Deploy VRF and Bridge Domain
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
  - name: Validate Input
    assert:
      that:
        - lab_name | regex_search("^lab[0-9]{1,3}-[0-9]{1,3}$")
      fail_msg: "Invalid lab_name variable entered, please correct and retry.  You entered: {{ lab_name }}"

  - name: Create VRF
    delegate_to: localhost
    cisco.aci.aci_vrf:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      vrf: "{{ aci.vrf }}"
      tenant: "{{ aci.tenant }}"
      policy_control_preference: "unenforced"
      policy_control_direction: "ingress"
      state: "present"
 
  - name: Create Bridge Domain
    delegate_to: localhost
    cisco.aci.aci_bd:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      tenant: "{{ aci.tenant }}"
      bd: "{{ aci.bd }}"
      vrf: "{{ aci.vrf }}"
      state: "present"

  - name: Create Bridge Domain Subnet
    delegate_to: localhost
    cisco.aci.aci_bd_subnet:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      tenant: "{{ aci.tenant }}"
      bd: "{{ aci.bd }}"
      gateway: "{{ aci.gw }}"
      mask: "24"
      state: "present"
      scope:
        - "public"
        - "shared"