---
- import_playbook: input_validation.yml

- name: Deploy JumpBox Contract
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
  - name: Consume Imported Contract On EPG
    delegate_to: localhost
    ignore_errors: yes
    cisco.aci.aci_rest:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: no
      path: "/api/node/mo/uni/tn-{{ aci.tenant }}/ap-{{ aci.ap }}/epg-{{ item }}.json"
      method: post
      content:
        fvRsConsIf:
          attributes:
            tnVzCPIfName: "LAB-SVC-L3Out"
            status: created
    with_items:
      "{{ aci.epg }}"