# !!!DISCLAIMER: DO NOT USE IN PRODUCTION ENVIRONMENT!!!
---
- name: Remove all VRFs BDs and APs
  hosts: localhost
  vars_files: vars.yml
  tasks:
  - name: Query all VRFs
    cisco.aci.aci_vrf:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      state: query
    delegate_to: localhost
    register: query_vrf
    
  - name: Remove a VRF for a tenant
    cisco.aci.aci_vrf:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      vrf: "{{ item.fvCtx.attributes.name }}"
      tenant: "{{ tenant }}"
      state: absent
    delegate_to: localhost
    loop: "{{ query_vrf.current.0.fvTenant.children }}"
    loop_control:
      label: "Deleting VRF: {{ item.fvCtx.attributes.name }}"
    ignore_errors: yes

  - name: Query all AP in Tn
    cisco.aci.aci_ap:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      state: query
    delegate_to: localhost
    register: query_ap

  - name: Remove the APs
    cisco.aci.aci_ap:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ item.fvAp.attributes.name }}"
      state: absent
    delegate_to: localhost
    loop: "{{ query_ap.current.0.fvTenant.children }}"
    loop_control:
      label: "Deleting AP: {{ item.fvAp.attributes.name }}"
    ignore_errors: yes

  - name: Query all Bridge Domains in Tn
    cisco.aci.aci_bd:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      state: query
    delegate_to: localhost
    register: query_bd

  - name: Delete all the Bridge Domains Found
    cisco.aci.aci_bd:
      host: "{{ aci_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      bd: "{{ item.fvBD.attributes.name }}"
      state: absent
    delegate_to: localhost     
    loop: "{{ query_bd.current.0.fvTenant.children }}"
    loop_control:
      label: "Deleting BD: {{ item.fvBD.attributes.name }}"
    ignore_errors: yes


 