# !!!DISCLAIMER: DO NOT USE IN PRODUCTION ENVIRONMENT!!!
---
- name: Remove all VRFs
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
  - name: Validate Input
    assert:
      that:
        - lab_name | regex_search("^lab[0-9]{1,3}-[0-9]{1,3}$")
      fail_msg: "Invalid lab_name variable entered, please correct and retry.  You entered: {{ lab_name }}"

  - name: Query VRFs
    delegate_to: localhost
    cisco.aci.aci_vrf:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      tenant: "{{ aci.tenant }}"
      state: "query"
    register: query_vrf
    
  - name: Remove VRFs
    delegate_to: localhost
    cisco.aci.aci_vrf:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: "no"
      vrf: "{{ item.fvCtx.attributes.name }}"
      tenant: "{{ aci.tenant }}"
      state: "absent"
    loop: "{{ query_vrf.current.0.fvTenant.children }}"
    loop_control:
      label: "Deleting VRF: {{ item.fvCtx.attributes.name }}"
    ignore_errors: "yes"