---
- import_playbook: input_validation.yml

- name: Enable preferred group on web and app EPGs
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
  - name: Toggle EPG preferred group
    delegate_to: localhost
    cisco.aci.aci_epg:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: no
      tenant: "{{ aci.tenant }}"
      ap: "{{ aci.ap }}"
      epg: "{{ item }}"
      bd: "{{ aci.bd }}"
      preferred_group: "yes"
      state: "present"
    with_items:
      "{{ aci.web_app_epg }}"