---
- name: User Input Validation
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
    - name: Validate Input
      assert:
        that:
          - lab_name | regex_search("^lab[0-9]{1,3}-[0-9]{1,3}$")
        fail_msg: "Invalid lab_name variable entered, please correct and retry.  You entered: {{ lab_name }}"