---
- import_playbook: input_validation.yml

- name: Configure VRF with enforcement and PG
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
  - name: Set VRF enforcement
    delegate_to: localhost
    cisco.aci.aci_vrf:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present

  - name: Enable VRF preferred group 
    delegate_to: localhost
    cisco.aci.aci_vrf:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: no
      tenant: "{{ aci.tenant }}"
      vrf: "{{ aci.vrf }}"
      preferred_group: "enabled"