---
- import_playbook: input_validation.yml

- name: Deploy JumpBox Contract
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
  - name: Consume imported contract on web and app EPGs
    delegate_to: localhost
    ignore_errors: yes
    cisco.aci.aci_epg_to_contract_interface:
      host: "{{ aci.hostname }}"
      username: "{{ aci.username }}"
      password: "{{ aci.password }}"
      validate_certs: no
      tenant: "{{ aci.tenant }}"
      ap: "{{ aci.ap }}"
      epg: "{{ item }}"
      contract_interface: "LAB-JB"
      state: "present"
    with_items:
      "{{ aci.web_app_epg }}"